"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import React, {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import { AnimatePresence, motion } from "framer-motion";
import dynamic from "next/dynamic";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faGithub,
  faLinkedinIn,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import { usePathname, useRouter } from "next/navigation";
import useResizeObserver from "@/hooks/useResizeObserver";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

// const DarkModeToggle = dynamic(() => import('dark-mode-toggle-animation'), { ssr: false })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({ children }: { children: React.ReactNode }) {
  // const [mainSectionHeight, setMainSectionHeight] = useState<number>(0);
  const mainSectionHeightRef = useRef<number>(0);
  // const [theme, setTheme] = useLocalStorage("theme", "light");
  const router = useRouter();

  const mainSectionRef = useRef<HTMLDivElement>(null);

  // useEffect(() => {
  //   console.log("HMMM", mainSectionRef.current?.scrollHeight);
  // }, []);

  // useEffect(() => {
  //   if (
  //     localStorage.theme === "dark" ||
  //     (!("theme" in localStorage) &&
  //       window.matchMedia("(prefers-color-scheme: dark)").matches)
  //   ) {
  //     document.getElementsByTagName("html")[0].classList.add("dark");
  //   } else {
  //     document.getElementsByTagName("html")[0].classList.remove("dark");
  //   }
  // }, []);
  //
  // useEffect(() => {
  //   if (theme == "dark") {
  //     document.getElementsByTagName("html")[0].classList.add("dark");
  //     localStorage.theme = "dark";
  //   } else {
  //     document.getElementsByTagName("html")[0].classList.remove("dark");
  //     localStorage.theme = "light";
  //   }
  // }, [theme]);

  // const toggleDarkMode = () => {
  //   if (theme == 'dark') {
  //     setTheme('light' as any)
  //   } else {
  //     setTheme('dark')
  //   }
  // }

  const measureCallBack = useCallback((ref: HTMLDivElement | null) => {
    // console.log("ssss", (ref?.firstChild as HTMLDivElement).scrollHeight);
    if (!mainSectionHeightRef.current) {
      mainSectionHeightRef.current =
        ((ref?.firstChild as HTMLDivElement)?.scrollHeight ?? 0) + 64;
    }
  }, []);

  return (
    <>
      <div className="fixed cursor-pointer top-3 right-3">
        {/*<DarkModeToggle*/}
        {/*    mode={theme == 'dark' ? 'sun' : 'moon'}*/}
        {/*    onClick={toggleDarkMode}*/}
        {/*    width="3rem"*/}
        {/*    moonColor="#334155"*/}
        {/*    sunColor="white"*/}
        {/*    animationDuration={1}*/}
        {/*/>*/}
      </div>
      <Navigation />
      <AnimatePresence>
        <motion.div
          layoutId="border-div"
          className="flex flex-col items-center justify-center w-full py-8 my-6 border-t-2 border-b-2 border-gray-300 border-white overflow-hidden"
          // initial={{ height: 0, opacity: 0 }}
          // animate={{
          //   height: `${mainSectionHeightRef.current}px`,
          //   opacity: 1,
          // }}
          // transition={{ duration: 1 }}
          // ref={measureCallBack}
        >
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            {children}
          </motion.div>
        </motion.div>
      </AnimatePresence>
      <Footer />
    </>
  );
}
